export const data = [{
    name: 'Travel Website',
    description: 'A website that shows details of a travel conference.',
    longdescription: 'The website will provide a comprehensive platform for attendees to access information on the upcoming travel conference. Some of the information that will be available on the website includes details about the event, keynote speakers, breakout sessions, networking opportunities, and more. In addition, the website will offer a variety of resources to help attendees prepare for the conference, such as travel tips, accommodation suggestions, and recommended activities to do in the host city. By providing a one-stop-shop for all conference-related information, the website aims to make the experience for attendees as smooth and enjoyable as possible.',
    imagesource: '/travel.png',
    altmessage: 'project1',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    projectsummary: ['Microverse', 'Front-End-Dev', '2023'],
    livelink: ['https://gaks1.github.io/capstone-project1/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/gaks1/capstone-project1', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '0',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  
  },
  {
    name: 'Hotel Booking App',
    description: 'An app that helps users book view and book hotels.',
    longdescription: "The website provides a comprehensive plartform with a React front-end and Ruby on Rails back-end. It uses an api tosend information to and from the back-end to the front-end. Users can view a list of hotel rooms they can then access more information on the hotel rooms allowing them to reserve a room. They can also view all reserved rooms and delete them when necessary. The website also has a login and signup feature that allows users to create an account and login to the website.",
    imagesource: '/hotel.png',
    altmessage: 'project2',
    technologies: ['React', 'Ruby on Rails', 'JavaScript', 'CSS' , 'Redux'],
    projectsummary: ['CANOPY', 'Back end dev', '2015'],
    livelink: ['https://hotel-booking-now.onrender.com/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/Jolak5/hotel-booking-app-backend', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '1',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  },
  {
    name: 'Budget App',
    description: 'A Ruby on Rails app that helps users manage their finances.',
    longdescription: "Money Mind is a Ruby on Rails web application designed for efficient financial management. Users can create and manage spending categories, input transactions with details, and monitor category-based totals. The app assists users in setting and tracking budgets, provides transaction history, ensures secure authentication, and offers a responsive design for convenient access from various devices. Money Mind empowers individuals to take control of their finances, make informed decisions, and achieve their financial goals effortlessly.",
    imagesource: '/budget.jpg',
    altmessage: 'project3',
    technologies: ['Ruby on Rails', 'CSS', 'Postgres', 'Rspec', 'Capybara'],
    projectsummary: ['CANOPY', 'Back end dev', '2015'],
    livelink: ['https://money-mind-h2z2.onrender.com/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/gaks1/budgetapp', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '2',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  
  },
  {
    name: 'Recipe App',
    description: 'A handy app that helps users manage their recipes. Making them public or private.',
    longdescription: "A recipe app that allows users to login using Devise. It allows them to add recipes and foods and delete them as well. the user can then make recipes public or private allowing for other users to see them or not. It also uses cancancan for authorization.",
    imagesource: '/recipe.png',
    altmessage: 'project4',
    technologies: ['Ruby on Rails', 'CSS', 'Postgres', 'Rspec', 'Capybara'],
    projectsummary: ['CANOPY', 'Back end dev', '2015'],
    livelink: ['https://recipe-app-y463.onrender.com/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/gaks1/recipe-app', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '3',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  
  },
  {
    name: 'Countries App',
    description: 'An appthat pulls country information from an api and displays it to the user.',
    longdescription: "A website that lists countries and territories in the world. It pulls data from an api and uses Redux to store and do state management. The app allows a user to see more details of a country when it is clicked on. It also allows the user to search for a country and filter the list of countries.",
    imagesource: '/countries.png',
    altmessage: 'project4',
    technologies: ['React', 'CSS', 'Jest', 'Redux'],
    projectsummary: ['CANOPY', 'Back end dev', '2015'],
    livelink: ['https://country-details.onrender.com/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/gaks1/Countries', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '3',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  
  },
  {
    name: 'Todo App',
    description: 'A handy app that helps users manage their todos.',
    longdescription: "The webapp uses html, css and javascript to create a todo app. It allows users to add todos and delete them as well. It also allows users to mark todos as complete and also to filter todos by completed and uncompleted todos.",
    imagesource: '/todo.png',
    altmessage: 'project4',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    projectsummary: ['CANOPY', 'Back end dev', '2015'],
    livelink: ['https://gaks1.github.io/To-do-list/dist/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/gaks1/To-do-list', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '3',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  
  },
  {
    name: 'Math Magicians',
    description: 'A math app for math enthusiasts with a calculator and a math quote generator.',
    longdescription: "The webapp uses React to create a math app. It allows users to do basic math calculations and also to generate math quotes. The quotes come from an api that is called when the user clicks on the quote in the navigation.",
    imagesource: '/math.png',
    altmessage: 'project4',
    technologies: ['React', 'CSS'],
    projectsummary: ['CANOPY', 'Back end dev', '2015'],
    livelink: ['https://isaac-math-magicians.onrender.com/', 'See live', 'img/seelive.png'],
    sourcelink: ['https://github.com/gaks1/Math-magicians', 'See Source', 'img/seesource.png'],
    buttontext: 'See Project',
    uniqueid: '3',
    counter: 'img/Counter.png',
    cancel: 'img/portfoliocancel.png',
  
  },
  ];